import 'LanguageController.dart';

class AppLocalizations {
  AppLocalizations._();

  static String tr(String key) {
    final lang = LanguageController.instance.language;
    final map = lang == 'French' ? _fr : _en;
    return map[key] ?? key;
  }

  // ── English ────────────────────────────────────────────────────────────────

  static const _en = <String, String>{
    // Common
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'remove': 'Remove',
    'add': 'Add',
    'yes': 'Yes',
    'no': 'No',
    'error': 'Error',
    'required': 'Required',
    'none': 'None',
    'leave': 'Leave',

    // Nav bar
    'nav_home': 'Home',
    'nav_history': 'History',
    'nav_money': 'Money',
    'nav_budget': 'Budget',
    'nav_family': 'Family',
    'nav_goals': 'Goals',

    // Home
    'home_welcome': 'Welcome back,',
    'home_total_balance': 'Total Balance',
    'home_spending_overview': 'Spending Overview',
    'home_recent_transactions': 'Recent Transactions',
    'home_see_all': 'See All',
    'home_no_transactions': 'No transactions yet',
    'home_income': 'Income',
    'home_expenses': 'Expenses',
    'home_savings': 'Savings',
    'home_today': 'Today',
    'home_yesterday': 'Yesterday',
    'home_days_ago': 'days ago',
    'home_this_month': 'This month',
    'home_this_month_btn': 'This Month',
    'home_savings_rate': 'Savings Rate',

    // Transaction History
    'history_title': 'Transaction History',
    'history_search': 'Search transactions...',
    'history_filter': 'Filter',
    'history_sort': 'Sort',
    'history_date': 'Date',
    'history_total_income': 'Total Income',
    'history_total_expenses': 'Total Expenses',
    'history_all_transactions': 'ALL TRANSACTIONS',
    'history_no_transactions': 'No transactions yet',
    'history_add_transaction': 'Add Transaction',
    'history_name': 'Name',
    'history_amount': 'Amount',
    'history_category': 'Category',
    'history_note_optional': 'Note (optional)',
    'history_save_transaction': 'Save Transaction',
    'history_income': 'Income',
    'history_expense': 'Expense',
    'history_transfer': 'Transfer',
    'history_filter_by_type': 'Filter by type',
    'history_sort_by': 'Sort by',
    'history_date_range': 'Date range',
    'history_all': 'All',
    'history_newest': 'Newest first',
    'history_oldest': 'Oldest first',
    'history_highest': 'Highest amount',
    'history_lowest': 'Lowest amount',
    'history_all_time': 'All time',
    'history_last_month': 'Last month',
    'history_last_7': 'Last 7 days',
    'history_last_7_label': 'Last 7d',
    'history_last_30': 'Last 30 days',
    'history_last_30_label': 'Last 30d',
    'history_new_category': '+ New category',
    'history_apply_goal': 'Apply to Goal (optional)',
    'history_valid_amount': 'Enter a valid amount.',
    'history_failed_save': 'Failed to save.',

    // Goals
    'goals_title': 'Finance Goals',
    'goals_subtitle': 'Track your financial dreams',
    'goals_overall_progress': 'Overall Progress',
    'goals_target': 'Target',
    'goals_pct_achieved': 'of your goals achieved',
    'goals_active': 'Active Goals',
    'goals_completed': 'Completed Goals',
    'goals_insights': 'Goal Insights',
    'goals_none_title': 'No goals yet',
    'goals_none_body': 'Set financial goals to track your progress\nand stay motivated.',
    'goals_add_first': 'Add First Goal',
    'goals_monthly': 'Monthly contribution',
    'goals_remaining': 'remaining',
    'goals_complete': 'complete',
    'goals_progress': 'Progress',
    'goals_delete_title': 'Delete Goal',
    'goals_delete_body': 'This cannot be undone.',
    'goals_add_title': 'Add New Goal',
    'goals_name': 'Goal Name',
    'goals_target_amount': 'Target Amount (\$)',
    'goals_current_savings': 'Current Savings (\$)',
    'goals_monthly_optional': 'Monthly Contribution (\$, optional)',
    'goals_type': 'Goal Type',
    'goals_target_date': 'Target Date',
    'goals_note_optional': 'Note (optional)',
    'goals_create': 'Create Goal',
    'goals_update_prefix': 'Update:',
    'goals_current_amount': 'Current Amount (\$)',
    'goals_save_progress': 'Save Progress',
    'goals_decrease_title': 'Decreasing goal amount',
    'goals_correction': 'Correction',
    'goals_withdrawal': 'Withdrawal',
    'goals_type_emergency': 'Emergency Fund',
    'goals_type_saving': 'Savings',
    'goals_type_purchase': 'Purchase',
    'goals_type_retirement': 'Retirement',
    'goals_type_debt': 'Debt Payoff',
    'goals_type_investment': 'Investment',
    'goals_type_spending': 'Spending',
    'goals_label_emergency': 'Emergency',
    'goals_label_saving': 'Savings',
    'goals_label_purchase': 'Purchase',
    'goals_label_retirement': 'Retirement',
    'goals_label_debt': 'Debt',
    'goals_label_investment': 'Investment',
    'goals_label_spending': 'Spending',

    // Family
    'family_plan': 'Family Plan',
    'family_budget': 'Family Budget',
    'family_spent': 'Spent',
    'family_members': 'Family Members',
    'family_shared_expenses': 'Shared Expenses',
    'family_insights': 'Family Insights',
    'family_setup_title': 'Create Your Family Plan',
    'family_setup_body': 'Track budgets and shared expenses\nwith your family members.',
    'family_create_btn': 'Create Family Plan',
    'family_no_members': 'No members yet. Add your first family member!',
    'family_no_expenses': 'No shared expenses yet. Add your first one!',
    'family_admin': 'Admin',
    'family_member': 'Member',
    'family_add_member_title': 'Add Family Member',
    'family_add_member_hint': 'Search by the email they used to sign up.',
    'family_email': 'Email Address',
    'family_look_up': 'Look Up',
    'family_not_found': 'No account found with that email.',
    'family_already_member': 'is already in this group.',
    'family_budget_alloc': 'Budget Allocation (\$)',
    'family_add_to_plan': 'Add to Family Plan',
    'family_add_expense_title': 'Add Shared Expense',
    'family_expense_name': 'Expense Name',
    'family_amount': 'Amount (\$)',
    'family_paid_by': 'Paid By',
    'family_category': 'Category',
    'family_add_expense_btn': 'Add Expense',
    'family_settings_title': 'Group Settings',
    'family_total_budget': 'Total Family Budget (\$)',
    'family_save_changes': 'Save Changes',
    'family_group_name': 'Family Name',
    'family_personal_budget': 'Your Personal Budget (\$)',
    'family_create_plan_btn': 'Create Plan',
    'family_remove_title': 'Remove Member',
    'family_cannot_remove_admin': 'Cannot remove the group admin.',
    'family_remove': 'Remove',
    'family_delete_expense_title': 'Delete Expense',
    'family_add_members_first': 'Add family members first before logging expenses.',
    'family_leave_title': 'Leave Group',
    'family_leave_confirm': 'Leave this family group?',
    'family_leave_btn': 'Leave',
    'family_per_person': '/person',
    'family_of': 'of',
    'family_paid_by_prefix': 'Paid by',

    // Profile Settings
    'profile_title': 'Profile & Settings',
    'profile_account': 'Account',
    'profile_edit': 'Edit Profile',
    'profile_change_password': 'Change Password',
    'profile_2fa': 'Two-Factor Authentication',
    'profile_preferences': 'Preferences',
    'profile_notifications': 'Notifications',
    'profile_dark_mode': 'Dark Mode',
    'profile_language': 'Language',
    'profile_support': 'Support',
    'profile_help': 'Help & Support',
    'profile_privacy': 'Privacy Policy',
    'profile_about': 'About',
    'profile_logout': 'Log Out',

    // Budget
    'budget_title': 'Budget Tracker',
    'budget_add': 'Add Budget',
    'budget_total': 'Total Budget',
    'budget_spent': 'Spent',
    'budget_remaining': 'Remaining',
    'budget_no_budgets': 'No budgets yet',
    'budget_over': 'Over budget',
    'budget_on_track': 'On track',
    'budget_near_limit': 'Near limit',

    // Money Flow
    'money_title': 'Money Flow',
    'money_income': 'Income',
    'money_expenses': 'Expenses',
    'money_net': 'Net Flow',
  };

  // ── French ─────────────────────────────────────────────────────────────────

  static const _fr = <String, String>{
    // Common
    'cancel': 'Annuler',
    'save': 'Enregistrer',
    'delete': 'Supprimer',
    'remove': 'Retirer',
    'add': 'Ajouter',
    'yes': 'Oui',
    'no': 'Non',
    'error': 'Erreur',
    'required': 'Requis',
    'none': 'Aucun',
    'leave': 'Quitter',

    // Nav bar
    'nav_home': 'Accueil',
    'nav_history': 'Historique',
    'nav_money': 'Argent',
    'nav_budget': 'Budget',
    'nav_family': 'Famille',
    'nav_goals': 'Objectifs',

    // Home
    'home_welcome': 'Bienvenue,',
    'home_total_balance': 'Solde total',
    'home_spending_overview': 'Aperçu des dépenses',
    'home_recent_transactions': 'Transactions récentes',
    'home_see_all': 'Voir tout',
    'home_no_transactions': 'Aucune transaction',
    'home_income': 'Revenus',
    'home_expenses': 'Dépenses',
    'home_savings': 'Épargne',
    'home_today': 'Aujourd\'hui',
    'home_yesterday': 'Hier',
    'home_days_ago': 'il y a {n} jours',
    'home_this_month': 'Ce mois',
    'home_this_month_btn': 'Ce mois',
    'home_savings_rate': 'Taux d\'épargne',

    // Transaction History
    'history_title': 'Historique des transactions',
    'history_search': 'Rechercher des transactions...',
    'history_filter': 'Filtrer',
    'history_sort': 'Trier',
    'history_date': 'Date',
    'history_total_income': 'Total des revenus',
    'history_total_expenses': 'Total des dépenses',
    'history_all_transactions': 'TOUTES LES TRANSACTIONS',
    'history_no_transactions': 'Aucune transaction',
    'history_add_transaction': 'Ajouter une transaction',
    'history_name': 'Nom',
    'history_amount': 'Montant',
    'history_category': 'Catégorie',
    'history_note_optional': 'Note (optionnel)',
    'history_save_transaction': 'Enregistrer',
    'history_income': 'Revenu',
    'history_expense': 'Dépense',
    'history_transfer': 'Transfert',
    'history_filter_by_type': 'Filtrer par type',
    'history_sort_by': 'Trier par',
    'history_date_range': 'Plage de dates',
    'history_all': 'Tous',
    'history_newest': 'Plus récent',
    'history_oldest': 'Plus ancien',
    'history_highest': 'Montant le plus élevé',
    'history_lowest': 'Montant le plus faible',
    'history_all_time': 'Tout le temps',
    'history_last_month': 'Mois dernier',
    'history_last_7': '7 derniers jours',
    'history_last_7_label': '7 derniers j.',
    'history_last_30': '30 derniers jours',
    'history_last_30_label': '30 derniers j.',
    'history_new_category': '+ Nouvelle catégorie',
    'history_apply_goal': 'Appliquer à un objectif (optionnel)',
    'history_valid_amount': 'Entrez un montant valide.',
    'history_failed_save': 'Échec de l\'enregistrement.',

    // Goals
    'goals_title': 'Objectifs financiers',
    'goals_subtitle': 'Suivez vos rêves financiers',
    'goals_overall_progress': 'Progression globale',
    'goals_target': 'Objectif',
    'goals_pct_achieved': 'de vos objectifs atteints',
    'goals_active': 'Objectifs actifs',
    'goals_completed': 'Objectifs complétés',
    'goals_insights': 'Aperçu des objectifs',
    'goals_none_title': 'Pas encore d\'objectifs',
    'goals_none_body': 'Définissez des objectifs financiers pour suivre\nvos progrès et rester motivé.',
    'goals_add_first': 'Premier objectif',
    'goals_monthly': 'Contribution mensuelle',
    'goals_remaining': 'restant',
    'goals_complete': 'complété',
    'goals_progress': 'Progression',
    'goals_delete_title': 'Supprimer l\'objectif',
    'goals_delete_body': 'Cette action est irréversible.',
    'goals_add_title': 'Nouvel objectif',
    'goals_name': 'Nom de l\'objectif',
    'goals_target_amount': 'Montant cible (\$)',
    'goals_current_savings': 'Épargne actuelle (\$)',
    'goals_monthly_optional': 'Contribution mensuelle (\$, optionnel)',
    'goals_type': 'Type d\'objectif',
    'goals_target_date': 'Date cible',
    'goals_note_optional': 'Note (optionnel)',
    'goals_create': 'Créer l\'objectif',
    'goals_update_prefix': 'Mise à jour :',
    'goals_current_amount': 'Montant actuel (\$)',
    'goals_save_progress': 'Enregistrer',
    'goals_decrease_title': 'Réduction du montant',
    'goals_correction': 'Correction',
    'goals_withdrawal': 'Retrait',
    'goals_type_emergency': 'Fonds d\'urgence',
    'goals_type_saving': 'Épargne',
    'goals_type_purchase': 'Achat',
    'goals_type_retirement': 'Retraite',
    'goals_type_debt': 'Remboursement de dette',
    'goals_type_investment': 'Investissement',
    'goals_type_spending': 'Dépenses',
    'goals_label_emergency': 'Urgence',
    'goals_label_saving': 'Épargne',
    'goals_label_purchase': 'Achat',
    'goals_label_retirement': 'Retraite',
    'goals_label_debt': 'Dette',
    'goals_label_investment': 'Investissement',
    'goals_label_spending': 'Dépenses',

    // Family
    'family_plan': 'Plan familial',
    'family_budget': 'Budget familial',
    'family_spent': 'Dépensé',
    'family_members': 'Membres de la famille',
    'family_shared_expenses': 'Dépenses partagées',
    'family_insights': 'Aperçu familial',
    'family_setup_title': 'Créez votre plan familial',
    'family_setup_body': 'Suivez les budgets et les dépenses partagées\navec vos proches.',
    'family_create_btn': 'Créer un plan familial',
    'family_no_members': 'Aucun membre. Ajoutez votre premier membre !',
    'family_no_expenses': 'Aucune dépense partagée. Ajoutez la première !',
    'family_admin': 'Administrateur',
    'family_member': 'Membre',
    'family_add_member_title': 'Ajouter un membre',
    'family_add_member_hint': 'Recherchez par l\'email utilisé lors de l\'inscription.',
    'family_email': 'Adresse e-mail',
    'family_look_up': 'Rechercher',
    'family_not_found': 'Aucun compte trouvé avec cet e-mail.',
    'family_already_member': 'est déjà dans ce groupe.',
    'family_budget_alloc': 'Allocation budgétaire (\$)',
    'family_add_to_plan': 'Ajouter au plan familial',
    'family_add_expense_title': 'Ajouter une dépense partagée',
    'family_expense_name': 'Nom de la dépense',
    'family_amount': 'Montant (\$)',
    'family_paid_by': 'Payé par',
    'family_category': 'Catégorie',
    'family_add_expense_btn': 'Ajouter la dépense',
    'family_settings_title': 'Paramètres du groupe',
    'family_total_budget': 'Budget familial total (\$)',
    'family_save_changes': 'Enregistrer',
    'family_group_name': 'Nom de la famille',
    'family_personal_budget': 'Votre budget personnel (\$)',
    'family_create_plan_btn': 'Créer le plan',
    'family_remove_title': 'Retirer le membre',
    'family_cannot_remove_admin': 'Impossible de retirer l\'administrateur.',
    'family_remove': 'Retirer',
    'family_delete_expense_title': 'Supprimer la dépense',
    'family_add_members_first': 'Ajoutez d\'abord des membres.',
    'family_leave_title': 'Quitter le groupe',
    'family_leave_confirm': 'Quitter ce groupe familial ?',
    'family_leave_btn': 'Quitter',
    'family_per_person': '/pers.',
    'family_of': 'sur',
    'family_paid_by_prefix': 'Payé par',

    // Profile Settings
    'profile_title': 'Profil et paramètres',
    'profile_account': 'Compte',
    'profile_edit': 'Modifier le profil',
    'profile_change_password': 'Changer le mot de passe',
    'profile_2fa': 'Authentification à deux facteurs',
    'profile_preferences': 'Préférences',
    'profile_notifications': 'Notifications',
    'profile_dark_mode': 'Mode sombre',
    'profile_language': 'Langue',
    'profile_support': 'Assistance',
    'profile_help': 'Aide et assistance',
    'profile_privacy': 'Politique de confidentialité',
    'profile_about': 'À propos',
    'profile_logout': 'Déconnexion',

    // Budget
    'budget_title': 'Suivi du budget',
    'budget_add': 'Ajouter un budget',
    'budget_total': 'Budget total',
    'budget_spent': 'Dépensé',
    'budget_remaining': 'Restant',
    'budget_no_budgets': 'Aucun budget',
    'budget_over': 'Dépassement',
    'budget_on_track': 'Dans les limites',
    'budget_near_limit': 'Proche de la limite',

    // Money Flow
    'money_title': 'Flux d\'argent',
    'money_income': 'Revenus',
    'money_expenses': 'Dépenses',
    'money_net': 'Flux net',
  };
}
