import 'LanguageController.dart';

/// Simple homemade i18n layer.
///
/// To add a new language:
///   1. Create a new `_xx` map below containing the same keys as `_en`.
///   2. Register it in [_languages] under the user-facing language name
///      (must match the strings used in [ProfileSettingsPage]'s dropdown).
///
/// Missing-key behaviour: if the picked language has no entry for a given
/// key, we fall back to English; if English is also missing, we return the
/// raw key so something always renders.
class AppLocalizations {
  AppLocalizations._();

  static String tr(String key) {
    final lang = LanguageController.instance.language;
    final map = _languages[lang] ?? _en;
    return map[key] ?? _en[key] ?? key;
  }

  static const _languages = <String, Map<String, String>>{
    'English': _en,
    'Spanish': _es,
    'French': _fr,
    'German': _de,
    'Chinese': _zh,
    'Japanese': _ja,
    'Vietnamese': _vi,
  };

  // ── English ────────────────────────────────────────────────────────────────

  static const _en = <String, String>{
    // Common
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'remove': 'Remove',
    'add': 'Add',
    'yes': 'Yes',
    'no': 'No',
    'error': 'Error',
    'required': 'Required',
    'none': 'None',
    'leave': 'Leave',

    // Nav bar
    'nav_home': 'Home',
    'nav_history': 'History',
    'nav_money': 'Money',
    'nav_budget': 'Budget',
    'nav_family': 'Family',
    'nav_goals': 'Goals',

    // Home
    'home_welcome': 'Welcome back,',
    'home_total_balance': 'Total Balance',
    'home_spending_overview': 'Spending Overview',
    'home_recent_transactions': 'Recent Transactions',
    'home_see_all': 'See All',
    'home_no_transactions': 'No transactions yet',
    'home_income': 'Income',
    'home_expenses': 'Expenses',
    'home_savings': 'Savings',
    'home_today': 'Today',
    'home_yesterday': 'Yesterday',
    'home_days_ago': 'days ago',
    'home_this_month': 'This month',
    'home_this_month_btn': 'This Month',
    'home_savings_rate': 'Savings Rate',

    // Transaction History
    'history_title': 'Transaction History',
    'history_search': 'Search transactions...',
    'history_filter': 'Filter',
    'history_sort': 'Sort',
    'history_date': 'Date',
    'history_total_income': 'Total Income',
    'history_total_expenses': 'Total Expenses',
    'history_all_transactions': 'ALL TRANSACTIONS',
    'history_no_transactions': 'No transactions yet',
    'history_add_transaction': 'Add Transaction',
    'history_name': 'Name',
    'history_amount': 'Amount',
    'history_category': 'Category',
    'history_note_optional': 'Note (optional)',
    'history_save_transaction': 'Save Transaction',
    'history_income': 'Income',
    'history_expense': 'Expense',
    'history_transfer': 'Transfer',
    'history_filter_by_type': 'Filter by type',
    'history_sort_by': 'Sort by',
    'history_date_range': 'Date range',
    'history_all': 'All',
    'history_newest': 'Newest first',
    'history_oldest': 'Oldest first',
    'history_highest': 'Highest amount',
    'history_lowest': 'Lowest amount',
    'history_all_time': 'All time',
    'history_last_month': 'Last month',
    'history_last_7': 'Last 7 days',
    'history_last_7_label': 'Last 7d',
    'history_last_30': 'Last 30 days',
    'history_last_30_label': 'Last 30d',
    'history_new_category': '+ New category',
    'history_apply_goal': 'Apply to Goal (optional)',
    'history_valid_amount': 'Enter a valid amount.',
    'history_failed_save': 'Failed to save.',

    // Goals
    'goals_title': 'Finance Goals',
    'goals_subtitle': 'Track your financial dreams',
    'goals_overall_progress': 'Overall Progress',
    'goals_target': 'Target',
    'goals_pct_achieved': 'of your goals achieved',
    'goals_active': 'Active Goals',
    'goals_completed': 'Completed Goals',
    'goals_insights': 'Goal Insights',
    'goals_none_title': 'No goals yet',
    'goals_none_body': 'Set financial goals to track your progress\nand stay motivated.',
    'goals_add_first': 'Add First Goal',
    'goals_monthly': 'Monthly contribution',
    'goals_remaining': 'remaining',
    'goals_complete': 'complete',
    'goals_progress': 'Progress',
    'goals_delete_title': 'Delete Goal',
    'goals_delete_body': 'This cannot be undone.',
    'goals_add_title': 'Add New Goal',
    'goals_name': 'Goal Name',
    'goals_target_amount': 'Target Amount (\$)',
    'goals_current_savings': 'Current Savings (\$)',
    'goals_monthly_optional': 'Monthly Contribution (\$, optional)',
    'goals_type': 'Goal Type',
    'goals_target_date': 'Target Date',
    'goals_note_optional': 'Note (optional)',
    'goals_create': 'Create Goal',
    'goals_update_prefix': 'Update:',
    'goals_current_amount': 'Current Amount (\$)',
    'goals_save_progress': 'Save Progress',
    'goals_decrease_title': 'Decreasing goal amount',
    'goals_correction': 'Correction',
    'goals_withdrawal': 'Withdrawal',
    'goals_type_emergency': 'Emergency Fund',
    'goals_type_saving': 'Savings',
    'goals_type_purchase': 'Purchase',
    'goals_type_retirement': 'Retirement',
    'goals_type_debt': 'Debt Payoff',
    'goals_type_investment': 'Investment',
    'goals_type_spending': 'Spending',
    'goals_label_emergency': 'Emergency',
    'goals_label_saving': 'Savings',
    'goals_label_purchase': 'Purchase',
    'goals_label_retirement': 'Retirement',
    'goals_label_debt': 'Debt',
    'goals_label_investment': 'Investment',
    'goals_label_spending': 'Spending',

    // Family
    'family_plan': 'Family Plan',
    'family_budget': 'Family Budget',
    'family_spent': 'Spent',
    'family_members': 'Family Members',
    'family_shared_expenses': 'Shared Expenses',
    'family_insights': 'Family Insights',
    'family_setup_title': 'Create Your Family Plan',
    'family_setup_body': 'Track budgets and shared expenses\nwith your family members.',
    'family_create_btn': 'Create Family Plan',
    'family_no_members': 'No members yet. Add your first family member!',
    'family_no_expenses': 'No shared expenses yet. Add your first one!',
    'family_admin': 'Admin',
    'family_member': 'Member',
    'family_add_member_title': 'Add Family Member',
    'family_add_member_hint': 'Search by the email they used to sign up.',
    'family_email': 'Email Address',
    'family_look_up': 'Look Up',
    'family_not_found': 'No account found with that email.',
    'family_already_member': 'is already in this group.',
    'family_budget_alloc': 'Budget Allocation (\$)',
    'family_add_to_plan': 'Add to Family Plan',
    'family_add_expense_title': 'Add Shared Expense',
    'family_expense_name': 'Expense Name',
    'family_amount': 'Amount (\$)',
    'family_paid_by': 'Paid By',
    'family_category': 'Category',
    'family_add_expense_btn': 'Add Expense',
    'family_settings_title': 'Group Settings',
    'family_total_budget': 'Total Family Budget (\$)',
    'family_save_changes': 'Save Changes',
    'family_group_name': 'Family Name',
    'family_personal_budget': 'Your Personal Budget (\$)',
    'family_create_plan_btn': 'Create Plan',
    'family_remove_title': 'Remove Member',
    'family_cannot_remove_admin': 'Cannot remove the group admin.',
    'family_remove': 'Remove',
    'family_delete_expense_title': 'Delete Expense',
    'family_add_members_first': 'Add family members first before logging expenses.',
    'family_leave_title': 'Leave Group',
    'family_leave_confirm': 'Leave this family group?',
    'family_leave_btn': 'Leave',
    'family_per_person': '/person',
    'family_of': 'of',
    'family_paid_by_prefix': 'Paid by',

    // Profile Settings
    'profile_title': 'Profile & Settings',
    'profile_account': 'Account',
    'profile_edit': 'Edit Profile',
    'profile_change_password': 'Change Password',
    'profile_2fa': 'Two-Factor Authentication',
    'profile_preferences': 'Preferences',
    'profile_notifications': 'Notifications',
    'profile_dark_mode': 'Dark Mode',
    'profile_language': 'Language',
    'profile_support': 'Support',
    'profile_help': 'Help & Support',
    'profile_privacy': 'Privacy Policy',
    'profile_about': 'About',
    'profile_logout': 'Log Out',

    // Budget
    'budget_title': 'Budget Tracker',
    'budget_add': 'Add Budget',
    'budget_total': 'Total Budget',
    'budget_spent': 'Spent',
    'budget_remaining': 'Remaining',
    'budget_no_budgets': 'No budgets yet',
    'budget_over': 'Over budget',
    'budget_on_track': 'On track',
    'budget_near_limit': 'Near limit',

    // Money Flow
    'money_title': 'Money Flow',
    'money_income': 'Income',
    'money_expenses': 'Expenses',
    'money_net': 'Net Flow',
    'money_failed_load': 'Failed to load data',
    'money_retry': 'Retry',
    'money_tab_overview': 'Overview',
    'money_net_cash_flow': 'Net Cash Flow',
    'money_saving_msg': 'Great job! You\'re saving this month.',
    'money_overspend_msg': 'Expenses exceed income this month.',
    'money_no_income_cats': 'No income categories this month.',
    'money_no_expense_cats': 'No expense categories this month.',
    'money_income_by_cat': 'Income by Category',
    'money_expenses_by_cat': 'Expenses by Category',
    'money_6mo_trend': '6-Month Trend',

    // Budget (extra)
    'budget_delete_title': 'Delete Budget',
    'budget_total_this_month': 'Total Budget This Month',
    'budget_alert': 'Budget Alert',
    'budget_alert_prefix': "You're approaching your limit in",
    'budget_alert_cat_one': 'category',
    'budget_alert_cat_many': 'categories',
    'budget_categories': 'Budget Categories',
    'budget_view_all': 'View All',
    'budget_all_categories': 'All Budget Categories',
    'budget_none_title': 'No budgets created yet',
    'budget_none_body': 'Set monthly limits for your spending\ncategories to stay on track.',
    'budget_create_btn': 'Create Budget',
    'budget_period_weekly': 'Weekly',
    'budget_period_monthly': 'Monthly',
    'budget_period_yearly': 'Yearly',
    'budget_over_by': 'Over budget by',
    'budget_used': 'used',
    'budget_left': 'left',
    'budget_tx_one': 'transaction',
    'budget_tx_many': 'transactions',
  };

  // ── Spanish ────────────────────────────────────────────────────────────────

  static const _es = <String, String>{
    'cancel': 'Cancelar',
    'save': 'Guardar',
    'delete': 'Eliminar',
    'remove': 'Quitar',
    'add': 'Añadir',
    'yes': 'Sí',
    'no': 'No',
    'error': 'Error',
    'required': 'Requerido',
    'none': 'Ninguno',
    'leave': 'Salir',

    'nav_home': 'Inicio',
    'nav_history': 'Historial',
    'nav_money': 'Dinero',
    'nav_budget': 'Presupuesto',
    'nav_family': 'Familia',
    'nav_goals': 'Metas',

    'home_welcome': 'Bienvenido,',
    'home_total_balance': 'Saldo total',
    'home_spending_overview': 'Resumen de gastos',
    'home_recent_transactions': 'Transacciones recientes',
    'home_see_all': 'Ver todo',
    'home_no_transactions': 'Sin transacciones',
    'home_income': 'Ingresos',
    'home_expenses': 'Gastos',
    'home_savings': 'Ahorros',
    'home_today': 'Hoy',
    'home_yesterday': 'Ayer',
    'home_days_ago': 'días atrás',
    'home_this_month': 'Este mes',
    'home_this_month_btn': 'Este mes',
    'home_savings_rate': 'Tasa de ahorro',

    'history_title': 'Historial de transacciones',
    'history_search': 'Buscar transacciones...',
    'history_filter': 'Filtrar',
    'history_sort': 'Ordenar',
    'history_date': 'Fecha',
    'history_total_income': 'Ingresos totales',
    'history_total_expenses': 'Gastos totales',
    'history_all_transactions': 'TODAS LAS TRANSACCIONES',
    'history_no_transactions': 'Sin transacciones',
    'history_add_transaction': 'Añadir transacción',
    'history_name': 'Nombre',
    'history_amount': 'Monto',
    'history_category': 'Categoría',
    'history_note_optional': 'Nota (opcional)',
    'history_save_transaction': 'Guardar',
    'history_income': 'Ingreso',
    'history_expense': 'Gasto',
    'history_transfer': 'Transferencia',
    'history_filter_by_type': 'Filtrar por tipo',
    'history_sort_by': 'Ordenar por',
    'history_date_range': 'Rango de fechas',
    'history_all': 'Todos',
    'history_newest': 'Más reciente',
    'history_oldest': 'Más antiguo',
    'history_highest': 'Monto más alto',
    'history_lowest': 'Monto más bajo',
    'history_all_time': 'Todo el tiempo',
    'history_last_month': 'Mes pasado',
    'history_last_7': 'Últimos 7 días',
    'history_last_7_label': 'Últ. 7d',
    'history_last_30': 'Últimos 30 días',
    'history_last_30_label': 'Últ. 30d',
    'history_new_category': '+ Nueva categoría',
    'history_apply_goal': 'Aplicar a meta (opcional)',
    'history_valid_amount': 'Ingrese un monto válido.',
    'history_failed_save': 'Error al guardar.',

    'goals_title': 'Metas financieras',
    'goals_subtitle': 'Sigue tus sueños financieros',
    'goals_overall_progress': 'Progreso general',
    'goals_target': 'Objetivo',
    'goals_pct_achieved': 'de tus metas alcanzadas',
    'goals_active': 'Metas activas',
    'goals_completed': 'Metas completadas',
    'goals_insights': 'Análisis de metas',
    'goals_none_title': 'Sin metas aún',
    'goals_none_body': 'Establece metas financieras para seguir\ntu progreso y mantenerte motivado.',
    'goals_add_first': 'Primera meta',
    'goals_monthly': 'Aporte mensual',
    'goals_remaining': 'restante',
    'goals_complete': 'completado',
    'goals_progress': 'Progreso',
    'goals_delete_title': 'Eliminar meta',
    'goals_delete_body': 'Esto no se puede deshacer.',
    'goals_add_title': 'Nueva meta',
    'goals_name': 'Nombre de la meta',
    'goals_target_amount': 'Monto objetivo (\$)',
    'goals_current_savings': 'Ahorros actuales (\$)',
    'goals_monthly_optional': 'Aporte mensual (\$, opcional)',
    'goals_type': 'Tipo de meta',
    'goals_target_date': 'Fecha objetivo',
    'goals_note_optional': 'Nota (opcional)',
    'goals_create': 'Crear meta',
    'goals_update_prefix': 'Actualizar:',
    'goals_current_amount': 'Monto actual (\$)',
    'goals_save_progress': 'Guardar',
    'goals_decrease_title': 'Reducir monto',
    'goals_correction': 'Corrección',
    'goals_withdrawal': 'Retiro',
    'goals_type_emergency': 'Fondo de emergencia',
    'goals_type_saving': 'Ahorros',
    'goals_type_purchase': 'Compra',
    'goals_type_retirement': 'Jubilación',
    'goals_type_debt': 'Pago de deuda',
    'goals_type_investment': 'Inversión',
    'goals_type_spending': 'Gasto',
    'goals_label_emergency': 'Emergencia',
    'goals_label_saving': 'Ahorros',
    'goals_label_purchase': 'Compra',
    'goals_label_retirement': 'Jubilación',
    'goals_label_debt': 'Deuda',
    'goals_label_investment': 'Inversión',
    'goals_label_spending': 'Gasto',

    'family_plan': 'Plan familiar',
    'family_budget': 'Presupuesto familiar',
    'family_spent': 'Gastado',
    'family_members': 'Miembros de la familia',
    'family_shared_expenses': 'Gastos compartidos',
    'family_insights': 'Análisis familiar',
    'family_setup_title': 'Crea tu plan familiar',
    'family_setup_body': 'Sigue los presupuestos y los gastos\ncompartidos con tu familia.',
    'family_create_btn': 'Crear plan familiar',
    'family_no_members': 'Sin miembros. ¡Añade al primero!',
    'family_no_expenses': 'Sin gastos compartidos. ¡Añade uno!',
    'family_admin': 'Administrador',
    'family_member': 'Miembro',
    'family_add_member_title': 'Añadir miembro',
    'family_add_member_hint': 'Busca por el correo que usaron al registrarse.',
    'family_email': 'Correo electrónico',
    'family_look_up': 'Buscar',
    'family_not_found': 'No se encontró cuenta con ese correo.',
    'family_already_member': 'ya está en este grupo.',
    'family_budget_alloc': 'Asignación de presupuesto (\$)',
    'family_add_to_plan': 'Añadir al plan',
    'family_add_expense_title': 'Añadir gasto compartido',
    'family_expense_name': 'Nombre del gasto',
    'family_amount': 'Monto (\$)',
    'family_paid_by': 'Pagado por',
    'family_category': 'Categoría',
    'family_add_expense_btn': 'Añadir gasto',
    'family_settings_title': 'Ajustes del grupo',
    'family_total_budget': 'Presupuesto familiar total (\$)',
    'family_save_changes': 'Guardar cambios',
    'family_group_name': 'Nombre de la familia',
    'family_personal_budget': 'Tu presupuesto personal (\$)',
    'family_create_plan_btn': 'Crear plan',
    'family_remove_title': 'Quitar miembro',
    'family_cannot_remove_admin': 'No se puede quitar al administrador.',
    'family_remove': 'Quitar',
    'family_delete_expense_title': 'Eliminar gasto',
    'family_add_members_first': 'Añade miembros antes de registrar gastos.',
    'family_leave_title': 'Salir del grupo',
    'family_leave_confirm': '¿Salir de este grupo familiar?',
    'family_leave_btn': 'Salir',
    'family_per_person': '/pers.',
    'family_of': 'de',
    'family_paid_by_prefix': 'Pagado por',

    'profile_title': 'Perfil y ajustes',
    'profile_account': 'Cuenta',
    'profile_edit': 'Editar perfil',
    'profile_change_password': 'Cambiar contraseña',
    'profile_2fa': 'Autenticación de dos factores',
    'profile_preferences': 'Preferencias',
    'profile_notifications': 'Notificaciones',
    'profile_dark_mode': 'Modo oscuro',
    'profile_language': 'Idioma',
    'profile_support': 'Soporte',
    'profile_help': 'Ayuda y soporte',
    'profile_privacy': 'Política de privacidad',
    'profile_about': 'Acerca de',
    'profile_logout': 'Cerrar sesión',

    'budget_title': 'Seguimiento de presupuesto',
    'budget_add': 'Añadir presupuesto',
    'budget_total': 'Presupuesto total',
    'budget_spent': 'Gastado',
    'budget_remaining': 'Restante',
    'budget_no_budgets': 'Sin presupuestos',
    'budget_over': 'Excedido',
    'budget_on_track': 'En camino',
    'budget_near_limit': 'Cerca del límite',

    'money_title': 'Flujo de dinero',
    'money_income': 'Ingresos',
    'money_expenses': 'Gastos',
    'money_net': 'Flujo neto',
    'money_failed_load': 'Error al cargar datos',
    'money_retry': 'Reintentar',
    'money_tab_overview': 'Resumen',
    'money_net_cash_flow': 'Flujo neto',
    'money_saving_msg': '¡Buen trabajo! Estás ahorrando este mes.',
    'money_overspend_msg': 'Los gastos superan los ingresos este mes.',
    'money_no_income_cats': 'Sin categorías de ingresos este mes.',
    'money_no_expense_cats': 'Sin categorías de gastos este mes.',
    'money_income_by_cat': 'Ingresos por categoría',
    'money_expenses_by_cat': 'Gastos por categoría',
    'money_6mo_trend': 'Tendencia de 6 meses',

    'budget_delete_title': 'Eliminar presupuesto',
    'budget_total_this_month': 'Presupuesto total este mes',
    'budget_alert': 'Alerta de presupuesto',
    'budget_alert_prefix': 'Te estás acercando al límite en',
    'budget_alert_cat_one': 'categoría',
    'budget_alert_cat_many': 'categorías',
    'budget_categories': 'Categorías de presupuesto',
    'budget_view_all': 'Ver todo',
    'budget_all_categories': 'Todas las categorías',
    'budget_none_title': 'Aún no hay presupuestos',
    'budget_none_body': 'Establece límites mensuales para tus categorías\nde gastos y mantente al día.',
    'budget_create_btn': 'Crear presupuesto',
    'budget_period_weekly': 'Semanal',
    'budget_period_monthly': 'Mensual',
    'budget_period_yearly': 'Anual',
    'budget_over_by': 'Excedido por',
    'budget_used': 'usado',
    'budget_left': 'restante',
    'budget_tx_one': 'transacción',
    'budget_tx_many': 'transacciones',
  };

  // ── French ─────────────────────────────────────────────────────────────────

  static const _fr = <String, String>{
    'cancel': 'Annuler',
    'save': 'Enregistrer',
    'delete': 'Supprimer',
    'remove': 'Retirer',
    'add': 'Ajouter',
    'yes': 'Oui',
    'no': 'Non',
    'error': 'Erreur',
    'required': 'Requis',
    'none': 'Aucun',
    'leave': 'Quitter',

    'nav_home': 'Accueil',
    'nav_history': 'Historique',
    'nav_money': 'Argent',
    'nav_budget': 'Budget',
    'nav_family': 'Famille',
    'nav_goals': 'Objectifs',

    'home_welcome': 'Bienvenue,',
    'home_total_balance': 'Solde total',
    'home_spending_overview': 'Aperçu des dépenses',
    'home_recent_transactions': 'Transactions récentes',
    'home_see_all': 'Voir tout',
    'home_no_transactions': 'Aucune transaction',
    'home_income': 'Revenus',
    'home_expenses': 'Dépenses',
    'home_savings': 'Épargne',
    'home_today': 'Aujourd\'hui',
    'home_yesterday': 'Hier',
    'home_days_ago': 'il y a {n} jours',
    'home_this_month': 'Ce mois',
    'home_this_month_btn': 'Ce mois',
    'home_savings_rate': 'Taux d\'épargne',

    'history_title': 'Historique des transactions',
    'history_search': 'Rechercher des transactions...',
    'history_filter': 'Filtrer',
    'history_sort': 'Trier',
    'history_date': 'Date',
    'history_total_income': 'Total des revenus',
    'history_total_expenses': 'Total des dépenses',
    'history_all_transactions': 'TOUTES LES TRANSACTIONS',
    'history_no_transactions': 'Aucune transaction',
    'history_add_transaction': 'Ajouter une transaction',
    'history_name': 'Nom',
    'history_amount': 'Montant',
    'history_category': 'Catégorie',
    'history_note_optional': 'Note (optionnel)',
    'history_save_transaction': 'Enregistrer',
    'history_income': 'Revenu',
    'history_expense': 'Dépense',
    'history_transfer': 'Transfert',
    'history_filter_by_type': 'Filtrer par type',
    'history_sort_by': 'Trier par',
    'history_date_range': 'Plage de dates',
    'history_all': 'Tous',
    'history_newest': 'Plus récent',
    'history_oldest': 'Plus ancien',
    'history_highest': 'Montant le plus élevé',
    'history_lowest': 'Montant le plus faible',
    'history_all_time': 'Tout le temps',
    'history_last_month': 'Mois dernier',
    'history_last_7': '7 derniers jours',
    'history_last_7_label': '7 derniers j.',
    'history_last_30': '30 derniers jours',
    'history_last_30_label': '30 derniers j.',
    'history_new_category': '+ Nouvelle catégorie',
    'history_apply_goal': 'Appliquer à un objectif (optionnel)',
    'history_valid_amount': 'Entrez un montant valide.',
    'history_failed_save': 'Échec de l\'enregistrement.',

    'goals_title': 'Objectifs financiers',
    'goals_subtitle': 'Suivez vos rêves financiers',
    'goals_overall_progress': 'Progression globale',
    'goals_target': 'Objectif',
    'goals_pct_achieved': 'de vos objectifs atteints',
    'goals_active': 'Objectifs actifs',
    'goals_completed': 'Objectifs complétés',
    'goals_insights': 'Aperçu des objectifs',
    'goals_none_title': 'Pas encore d\'objectifs',
    'goals_none_body': 'Définissez des objectifs financiers pour suivre\nvos progrès et rester motivé.',
    'goals_add_first': 'Premier objectif',
    'goals_monthly': 'Contribution mensuelle',
    'goals_remaining': 'restant',
    'goals_complete': 'complété',
    'goals_progress': 'Progression',
    'goals_delete_title': 'Supprimer l\'objectif',
    'goals_delete_body': 'Cette action est irréversible.',
    'goals_add_title': 'Nouvel objectif',
    'goals_name': 'Nom de l\'objectif',
    'goals_target_amount': 'Montant cible (\$)',
    'goals_current_savings': 'Épargne actuelle (\$)',
    'goals_monthly_optional': 'Contribution mensuelle (\$, optionnel)',
    'goals_type': 'Type d\'objectif',
    'goals_target_date': 'Date cible',
    'goals_note_optional': 'Note (optionnel)',
    'goals_create': 'Créer l\'objectif',
    'goals_update_prefix': 'Mise à jour :',
    'goals_current_amount': 'Montant actuel (\$)',
    'goals_save_progress': 'Enregistrer',
    'goals_decrease_title': 'Réduction du montant',
    'goals_correction': 'Correction',
    'goals_withdrawal': 'Retrait',
    'goals_type_emergency': 'Fonds d\'urgence',
    'goals_type_saving': 'Épargne',
    'goals_type_purchase': 'Achat',
    'goals_type_retirement': 'Retraite',
    'goals_type_debt': 'Remboursement de dette',
    'goals_type_investment': 'Investissement',
    'goals_type_spending': 'Dépenses',
    'goals_label_emergency': 'Urgence',
    'goals_label_saving': 'Épargne',
    'goals_label_purchase': 'Achat',
    'goals_label_retirement': 'Retraite',
    'goals_label_debt': 'Dette',
    'goals_label_investment': 'Investissement',
    'goals_label_spending': 'Dépenses',

    'family_plan': 'Plan familial',
    'family_budget': 'Budget familial',
    'family_spent': 'Dépensé',
    'family_members': 'Membres de la famille',
    'family_shared_expenses': 'Dépenses partagées',
    'family_insights': 'Aperçu familial',
    'family_setup_title': 'Créez votre plan familial',
    'family_setup_body': 'Suivez les budgets et les dépenses partagées\navec vos proches.',
    'family_create_btn': 'Créer un plan familial',
    'family_no_members': 'Aucun membre. Ajoutez votre premier membre !',
    'family_no_expenses': 'Aucune dépense partagée. Ajoutez la première !',
    'family_admin': 'Administrateur',
    'family_member': 'Membre',
    'family_add_member_title': 'Ajouter un membre',
    'family_add_member_hint': 'Recherchez par l\'email utilisé lors de l\'inscription.',
    'family_email': 'Adresse e-mail',
    'family_look_up': 'Rechercher',
    'family_not_found': 'Aucun compte trouvé avec cet e-mail.',
    'family_already_member': 'est déjà dans ce groupe.',
    'family_budget_alloc': 'Allocation budgétaire (\$)',
    'family_add_to_plan': 'Ajouter au plan familial',
    'family_add_expense_title': 'Ajouter une dépense partagée',
    'family_expense_name': 'Nom de la dépense',
    'family_amount': 'Montant (\$)',
    'family_paid_by': 'Payé par',
    'family_category': 'Catégorie',
    'family_add_expense_btn': 'Ajouter la dépense',
    'family_settings_title': 'Paramètres du groupe',
    'family_total_budget': 'Budget familial total (\$)',
    'family_save_changes': 'Enregistrer',
    'family_group_name': 'Nom de la famille',
    'family_personal_budget': 'Votre budget personnel (\$)',
    'family_create_plan_btn': 'Créer le plan',
    'family_remove_title': 'Retirer le membre',
    'family_cannot_remove_admin': 'Impossible de retirer l\'administrateur.',
    'family_remove': 'Retirer',
    'family_delete_expense_title': 'Supprimer la dépense',
    'family_add_members_first': 'Ajoutez d\'abord des membres.',
    'family_leave_title': 'Quitter le groupe',
    'family_leave_confirm': 'Quitter ce groupe familial ?',
    'family_leave_btn': 'Quitter',
    'family_per_person': '/pers.',
    'family_of': 'sur',
    'family_paid_by_prefix': 'Payé par',

    'profile_title': 'Profil et paramètres',
    'profile_account': 'Compte',
    'profile_edit': 'Modifier le profil',
    'profile_change_password': 'Changer le mot de passe',
    'profile_2fa': 'Authentification à deux facteurs',
    'profile_preferences': 'Préférences',
    'profile_notifications': 'Notifications',
    'profile_dark_mode': 'Mode sombre',
    'profile_language': 'Langue',
    'profile_support': 'Assistance',
    'profile_help': 'Aide et assistance',
    'profile_privacy': 'Politique de confidentialité',
    'profile_about': 'À propos',
    'profile_logout': 'Déconnexion',

    'budget_title': 'Suivi du budget',
    'budget_add': 'Ajouter un budget',
    'budget_total': 'Budget total',
    'budget_spent': 'Dépensé',
    'budget_remaining': 'Restant',
    'budget_no_budgets': 'Aucun budget',
    'budget_over': 'Dépassement',
    'budget_on_track': 'Dans les limites',
    'budget_near_limit': 'Proche de la limite',

    'money_title': 'Flux d\'argent',
    'money_income': 'Revenus',
    'money_expenses': 'Dépenses',
    'money_net': 'Flux net',
    'money_failed_load': 'Échec du chargement',
    'money_retry': 'Réessayer',
    'money_tab_overview': 'Aperçu',
    'money_net_cash_flow': 'Flux net',
    'money_saving_msg': 'Bravo ! Vous épargnez ce mois.',
    'money_overspend_msg': 'Les dépenses dépassent les revenus ce mois.',
    'money_no_income_cats': 'Aucune catégorie de revenus ce mois.',
    'money_no_expense_cats': 'Aucune catégorie de dépenses ce mois.',
    'money_income_by_cat': 'Revenus par catégorie',
    'money_expenses_by_cat': 'Dépenses par catégorie',
    'money_6mo_trend': 'Tendance sur 6 mois',

    'budget_delete_title': 'Supprimer le budget',
    'budget_total_this_month': 'Budget total ce mois',
    'budget_alert': 'Alerte budget',
    'budget_alert_prefix': 'Vous approchez de la limite dans',
    'budget_alert_cat_one': 'catégorie',
    'budget_alert_cat_many': 'catégories',
    'budget_categories': 'Catégories de budget',
    'budget_view_all': 'Voir tout',
    'budget_all_categories': 'Toutes les catégories',
    'budget_none_title': 'Aucun budget créé',
    'budget_none_body': 'Définissez des limites mensuelles pour vos\ncatégories de dépenses.',
    'budget_create_btn': 'Créer un budget',
    'budget_period_weekly': 'Hebdomadaire',
    'budget_period_monthly': 'Mensuel',
    'budget_period_yearly': 'Annuel',
    'budget_over_by': 'Dépassement de',
    'budget_used': 'utilisé',
    'budget_left': 'restant',
    'budget_tx_one': 'transaction',
    'budget_tx_many': 'transactions',
  };

  // ── German ─────────────────────────────────────────────────────────────────

  static const _de = <String, String>{
    'cancel': 'Abbrechen',
    'save': 'Speichern',
    'delete': 'Löschen',
    'remove': 'Entfernen',
    'add': 'Hinzufügen',
    'yes': 'Ja',
    'no': 'Nein',
    'error': 'Fehler',
    'required': 'Erforderlich',
    'none': 'Keine',
    'leave': 'Verlassen',

    'nav_home': 'Start',
    'nav_history': 'Verlauf',
    'nav_money': 'Geld',
    'nav_budget': 'Budget',
    'nav_family': 'Familie',
    'nav_goals': 'Ziele',

    'home_welcome': 'Willkommen zurück,',
    'home_total_balance': 'Gesamtsaldo',
    'home_spending_overview': 'Ausgabenübersicht',
    'home_recent_transactions': 'Letzte Transaktionen',
    'home_see_all': 'Alle anzeigen',
    'home_no_transactions': 'Keine Transaktionen',
    'home_income': 'Einnahmen',
    'home_expenses': 'Ausgaben',
    'home_savings': 'Ersparnisse',
    'home_today': 'Heute',
    'home_yesterday': 'Gestern',
    'home_days_ago': 'Tage her',
    'home_this_month': 'Diesen Monat',
    'home_this_month_btn': 'Diesen Monat',
    'home_savings_rate': 'Sparquote',

    'history_title': 'Transaktionsverlauf',
    'history_search': 'Transaktionen suchen...',
    'history_filter': 'Filtern',
    'history_sort': 'Sortieren',
    'history_date': 'Datum',
    'history_total_income': 'Gesamteinnahmen',
    'history_total_expenses': 'Gesamtausgaben',
    'history_all_transactions': 'ALLE TRANSAKTIONEN',
    'history_no_transactions': 'Keine Transaktionen',
    'history_add_transaction': 'Transaktion hinzufügen',
    'history_name': 'Name',
    'history_amount': 'Betrag',
    'history_category': 'Kategorie',
    'history_note_optional': 'Notiz (optional)',
    'history_save_transaction': 'Speichern',
    'history_income': 'Einnahme',
    'history_expense': 'Ausgabe',
    'history_transfer': 'Überweisung',
    'history_filter_by_type': 'Nach Typ filtern',
    'history_sort_by': 'Sortieren nach',
    'history_date_range': 'Datumsbereich',
    'history_all': 'Alle',
    'history_newest': 'Neueste zuerst',
    'history_oldest': 'Älteste zuerst',
    'history_highest': 'Höchster Betrag',
    'history_lowest': 'Niedrigster Betrag',
    'history_all_time': 'Gesamt',
    'history_last_month': 'Letzter Monat',
    'history_last_7': 'Letzte 7 Tage',
    'history_last_7_label': 'Letzte 7T',
    'history_last_30': 'Letzte 30 Tage',
    'history_last_30_label': 'Letzte 30T',
    'history_new_category': '+ Neue Kategorie',
    'history_apply_goal': 'Auf Ziel anwenden (optional)',
    'history_valid_amount': 'Gültigen Betrag eingeben.',
    'history_failed_save': 'Speichern fehlgeschlagen.',

    'goals_title': 'Finanzielle Ziele',
    'goals_subtitle': 'Verfolge deine finanziellen Träume',
    'goals_overall_progress': 'Gesamtfortschritt',
    'goals_target': 'Ziel',
    'goals_pct_achieved': 'deiner Ziele erreicht',
    'goals_active': 'Aktive Ziele',
    'goals_completed': 'Erreichte Ziele',
    'goals_insights': 'Ziel-Einblicke',
    'goals_none_title': 'Noch keine Ziele',
    'goals_none_body': 'Setze finanzielle Ziele, um deinen Fortschritt\nzu verfolgen und motiviert zu bleiben.',
    'goals_add_first': 'Erstes Ziel',
    'goals_monthly': 'Monatlicher Beitrag',
    'goals_remaining': 'verbleibend',
    'goals_complete': 'abgeschlossen',
    'goals_progress': 'Fortschritt',
    'goals_delete_title': 'Ziel löschen',
    'goals_delete_body': 'Dies kann nicht rückgängig gemacht werden.',
    'goals_add_title': 'Neues Ziel',
    'goals_name': 'Zielname',
    'goals_target_amount': 'Zielbetrag (\$)',
    'goals_current_savings': 'Aktuelle Ersparnisse (\$)',
    'goals_monthly_optional': 'Monatlicher Beitrag (\$, optional)',
    'goals_type': 'Zieltyp',
    'goals_target_date': 'Zieldatum',
    'goals_note_optional': 'Notiz (optional)',
    'goals_create': 'Ziel erstellen',
    'goals_update_prefix': 'Aktualisieren:',
    'goals_current_amount': 'Aktueller Betrag (\$)',
    'goals_save_progress': 'Speichern',
    'goals_decrease_title': 'Betrag reduzieren',
    'goals_correction': 'Korrektur',
    'goals_withdrawal': 'Abhebung',
    'goals_type_emergency': 'Notfallfonds',
    'goals_type_saving': 'Ersparnisse',
    'goals_type_purchase': 'Kauf',
    'goals_type_retirement': 'Ruhestand',
    'goals_type_debt': 'Schuldenabbau',
    'goals_type_investment': 'Investition',
    'goals_type_spending': 'Ausgaben',
    'goals_label_emergency': 'Notfall',
    'goals_label_saving': 'Ersparnisse',
    'goals_label_purchase': 'Kauf',
    'goals_label_retirement': 'Ruhestand',
    'goals_label_debt': 'Schulden',
    'goals_label_investment': 'Investition',
    'goals_label_spending': 'Ausgaben',

    'family_plan': 'Familienplan',
    'family_budget': 'Familienbudget',
    'family_spent': 'Ausgegeben',
    'family_members': 'Familienmitglieder',
    'family_shared_expenses': 'Geteilte Ausgaben',
    'family_insights': 'Familieneinblicke',
    'family_setup_title': 'Erstelle deinen Familienplan',
    'family_setup_body': 'Verfolge Budgets und geteilte Ausgaben\nmit deinen Familienmitgliedern.',
    'family_create_btn': 'Familienplan erstellen',
    'family_no_members': 'Keine Mitglieder. Füge das erste hinzu!',
    'family_no_expenses': 'Keine geteilten Ausgaben. Füge die erste hinzu!',
    'family_admin': 'Administrator',
    'family_member': 'Mitglied',
    'family_add_member_title': 'Mitglied hinzufügen',
    'family_add_member_hint': 'Suche per E-Mail, die bei der Anmeldung verwendet wurde.',
    'family_email': 'E-Mail-Adresse',
    'family_look_up': 'Suchen',
    'family_not_found': 'Kein Konto mit dieser E-Mail gefunden.',
    'family_already_member': 'ist bereits in dieser Gruppe.',
    'family_budget_alloc': 'Budgetzuteilung (\$)',
    'family_add_to_plan': 'Zum Plan hinzufügen',
    'family_add_expense_title': 'Geteilte Ausgabe hinzufügen',
    'family_expense_name': 'Ausgabenname',
    'family_amount': 'Betrag (\$)',
    'family_paid_by': 'Bezahlt von',
    'family_category': 'Kategorie',
    'family_add_expense_btn': 'Ausgabe hinzufügen',
    'family_settings_title': 'Gruppeneinstellungen',
    'family_total_budget': 'Gesamtfamilienbudget (\$)',
    'family_save_changes': 'Änderungen speichern',
    'family_group_name': 'Familienname',
    'family_personal_budget': 'Dein persönliches Budget (\$)',
    'family_create_plan_btn': 'Plan erstellen',
    'family_remove_title': 'Mitglied entfernen',
    'family_cannot_remove_admin': 'Administrator kann nicht entfernt werden.',
    'family_remove': 'Entfernen',
    'family_delete_expense_title': 'Ausgabe löschen',
    'family_add_members_first': 'Füge zuerst Mitglieder hinzu.',
    'family_leave_title': 'Gruppe verlassen',
    'family_leave_confirm': 'Diese Familiengruppe verlassen?',
    'family_leave_btn': 'Verlassen',
    'family_per_person': '/Pers.',
    'family_of': 'von',
    'family_paid_by_prefix': 'Bezahlt von',

    'profile_title': 'Profil & Einstellungen',
    'profile_account': 'Konto',
    'profile_edit': 'Profil bearbeiten',
    'profile_change_password': 'Passwort ändern',
    'profile_2fa': 'Zwei-Faktor-Authentifizierung',
    'profile_preferences': 'Einstellungen',
    'profile_notifications': 'Benachrichtigungen',
    'profile_dark_mode': 'Dunkler Modus',
    'profile_language': 'Sprache',
    'profile_support': 'Support',
    'profile_help': 'Hilfe & Support',
    'profile_privacy': 'Datenschutzrichtlinie',
    'profile_about': 'Über',
    'profile_logout': 'Abmelden',

    'budget_title': 'Budgetverfolgung',
    'budget_add': 'Budget hinzufügen',
    'budget_total': 'Gesamtbudget',
    'budget_spent': 'Ausgegeben',
    'budget_remaining': 'Verbleibend',
    'budget_no_budgets': 'Keine Budgets',
    'budget_over': 'Überschritten',
    'budget_on_track': 'Im Plan',
    'budget_near_limit': 'Nahe Limit',

    'money_title': 'Geldfluss',
    'money_income': 'Einnahmen',
    'money_expenses': 'Ausgaben',
    'money_net': 'Nettofluss',
    'money_failed_load': 'Daten konnten nicht geladen werden',
    'money_retry': 'Erneut versuchen',
    'money_tab_overview': 'Übersicht',
    'money_net_cash_flow': 'Nettofluss',
    'money_saving_msg': 'Gut gemacht! Du sparst diesen Monat.',
    'money_overspend_msg': 'Die Ausgaben übersteigen die Einnahmen.',
    'money_no_income_cats': 'Keine Einnahmenkategorien diesen Monat.',
    'money_no_expense_cats': 'Keine Ausgabenkategorien diesen Monat.',
    'money_income_by_cat': 'Einnahmen nach Kategorie',
    'money_expenses_by_cat': 'Ausgaben nach Kategorie',
    'money_6mo_trend': '6-Monats-Trend',

    'budget_delete_title': 'Budget löschen',
    'budget_total_this_month': 'Gesamtbudget diesen Monat',
    'budget_alert': 'Budget-Warnung',
    'budget_alert_prefix': 'Du näherst dich der Grenze in',
    'budget_alert_cat_one': 'Kategorie',
    'budget_alert_cat_many': 'Kategorien',
    'budget_categories': 'Budgetkategorien',
    'budget_view_all': 'Alle anzeigen',
    'budget_all_categories': 'Alle Budgetkategorien',
    'budget_none_title': 'Noch keine Budgets erstellt',
    'budget_none_body': 'Setze monatliche Limits für deine\nAusgabenkategorien.',
    'budget_create_btn': 'Budget erstellen',
    'budget_period_weekly': 'Wöchentlich',
    'budget_period_monthly': 'Monatlich',
    'budget_period_yearly': 'Jährlich',
    'budget_over_by': 'Überschritten um',
    'budget_used': 'verwendet',
    'budget_left': 'übrig',
    'budget_tx_one': 'Transaktion',
    'budget_tx_many': 'Transaktionen',
  };

  // ── Chinese (Simplified) ───────────────────────────────────────────────────

  static const _zh = <String, String>{
    'cancel': '取消',
    'save': '保存',
    'delete': '删除',
    'remove': '移除',
    'add': '添加',
    'yes': '是',
    'no': '否',
    'error': '错误',
    'required': '必填',
    'none': '无',
    'leave': '离开',

    'nav_home': '主页',
    'nav_history': '历史',
    'nav_money': '资金',
    'nav_budget': '预算',
    'nav_family': '家庭',
    'nav_goals': '目标',

    'home_welcome': '欢迎回来,',
    'home_total_balance': '总余额',
    'home_spending_overview': '支出概览',
    'home_recent_transactions': '近期交易',
    'home_see_all': '查看全部',
    'home_no_transactions': '暂无交易',
    'home_income': '收入',
    'home_expenses': '支出',
    'home_savings': '储蓄',
    'home_today': '今天',
    'home_yesterday': '昨天',
    'home_days_ago': '天前',
    'home_this_month': '本月',
    'home_this_month_btn': '本月',
    'home_savings_rate': '储蓄率',

    'history_title': '交易历史',
    'history_search': '搜索交易...',
    'history_filter': '筛选',
    'history_sort': '排序',
    'history_date': '日期',
    'history_total_income': '总收入',
    'history_total_expenses': '总支出',
    'history_all_transactions': '所有交易',
    'history_no_transactions': '暂无交易',
    'history_add_transaction': '添加交易',
    'history_name': '名称',
    'history_amount': '金额',
    'history_category': '类别',
    'history_note_optional': '备注（可选）',
    'history_save_transaction': '保存',
    'history_income': '收入',
    'history_expense': '支出',
    'history_transfer': '转账',
    'history_filter_by_type': '按类型筛选',
    'history_sort_by': '排序方式',
    'history_date_range': '日期范围',
    'history_all': '全部',
    'history_newest': '最新优先',
    'history_oldest': '最早优先',
    'history_highest': '金额最高',
    'history_lowest': '金额最低',
    'history_all_time': '全部时间',
    'history_last_month': '上个月',
    'history_last_7': '过去7天',
    'history_last_7_label': '7天',
    'history_last_30': '过去30天',
    'history_last_30_label': '30天',
    'history_new_category': '+ 新类别',
    'history_apply_goal': '应用到目标（可选）',
    'history_valid_amount': '请输入有效金额。',
    'history_failed_save': '保存失败。',

    'goals_title': '财务目标',
    'goals_subtitle': '追踪您的财务梦想',
    'goals_overall_progress': '总体进度',
    'goals_target': '目标',
    'goals_pct_achieved': '已达成的目标',
    'goals_active': '进行中',
    'goals_completed': '已完成',
    'goals_insights': '目标洞察',
    'goals_none_title': '暂无目标',
    'goals_none_body': '设定财务目标以追踪进度\n并保持动力。',
    'goals_add_first': '添加首个目标',
    'goals_monthly': '每月供款',
    'goals_remaining': '剩余',
    'goals_complete': '完成',
    'goals_progress': '进度',
    'goals_delete_title': '删除目标',
    'goals_delete_body': '此操作无法撤销。',
    'goals_add_title': '新建目标',
    'goals_name': '目标名称',
    'goals_target_amount': '目标金额 (\$)',
    'goals_current_savings': '当前储蓄 (\$)',
    'goals_monthly_optional': '每月供款 (\$，可选)',
    'goals_type': '目标类型',
    'goals_target_date': '目标日期',
    'goals_note_optional': '备注（可选）',
    'goals_create': '创建目标',
    'goals_update_prefix': '更新：',
    'goals_current_amount': '当前金额 (\$)',
    'goals_save_progress': '保存进度',
    'goals_decrease_title': '减少目标金额',
    'goals_correction': '更正',
    'goals_withdrawal': '提取',
    'goals_type_emergency': '应急基金',
    'goals_type_saving': '储蓄',
    'goals_type_purchase': '购买',
    'goals_type_retirement': '退休',
    'goals_type_debt': '偿还债务',
    'goals_type_investment': '投资',
    'goals_type_spending': '支出',
    'goals_label_emergency': '应急',
    'goals_label_saving': '储蓄',
    'goals_label_purchase': '购买',
    'goals_label_retirement': '退休',
    'goals_label_debt': '债务',
    'goals_label_investment': '投资',
    'goals_label_spending': '支出',

    'family_plan': '家庭计划',
    'family_budget': '家庭预算',
    'family_spent': '已支出',
    'family_members': '家庭成员',
    'family_shared_expenses': '共享开支',
    'family_insights': '家庭洞察',
    'family_setup_title': '创建您的家庭计划',
    'family_setup_body': '与家人一同追踪预算\n和共享开支。',
    'family_create_btn': '创建家庭计划',
    'family_no_members': '暂无成员。添加第一位成员吧！',
    'family_no_expenses': '暂无共享开支。添加一项吧！',
    'family_admin': '管理员',
    'family_member': '成员',
    'family_add_member_title': '添加家庭成员',
    'family_add_member_hint': '按注册时使用的电子邮件搜索。',
    'family_email': '电子邮件',
    'family_look_up': '查找',
    'family_not_found': '未找到使用该邮箱的账户。',
    'family_already_member': '已在该群组中。',
    'family_budget_alloc': '预算分配 (\$)',
    'family_add_to_plan': '加入家庭计划',
    'family_add_expense_title': '添加共享开支',
    'family_expense_name': '开支名称',
    'family_amount': '金额 (\$)',
    'family_paid_by': '支付人',
    'family_category': '类别',
    'family_add_expense_btn': '添加开支',
    'family_settings_title': '群组设置',
    'family_total_budget': '家庭总预算 (\$)',
    'family_save_changes': '保存更改',
    'family_group_name': '家庭名称',
    'family_personal_budget': '您的个人预算 (\$)',
    'family_create_plan_btn': '创建计划',
    'family_remove_title': '移除成员',
    'family_cannot_remove_admin': '无法移除管理员。',
    'family_remove': '移除',
    'family_delete_expense_title': '删除开支',
    'family_add_members_first': '请先添加成员再记录开支。',
    'family_leave_title': '离开群组',
    'family_leave_confirm': '离开此家庭群组？',
    'family_leave_btn': '离开',
    'family_per_person': '/人',
    'family_of': '/',
    'family_paid_by_prefix': '由',

    'profile_title': '个人资料与设置',
    'profile_account': '账户',
    'profile_edit': '编辑资料',
    'profile_change_password': '更改密码',
    'profile_2fa': '双重身份验证',
    'profile_preferences': '偏好设置',
    'profile_notifications': '通知',
    'profile_dark_mode': '深色模式',
    'profile_language': '语言',
    'profile_support': '支持',
    'profile_help': '帮助与支持',
    'profile_privacy': '隐私政策',
    'profile_about': '关于',
    'profile_logout': '退出登录',

    'budget_title': '预算跟踪',
    'budget_add': '添加预算',
    'budget_total': '总预算',
    'budget_spent': '已支出',
    'budget_remaining': '剩余',
    'budget_no_budgets': '暂无预算',
    'budget_over': '超出预算',
    'budget_on_track': '正常',
    'budget_near_limit': '接近上限',

    'money_title': '资金流',
    'money_income': '收入',
    'money_expenses': '支出',
    'money_net': '净流量',
    'money_failed_load': '加载数据失败',
    'money_retry': '重试',
    'money_tab_overview': '概览',
    'money_net_cash_flow': '净现金流',
    'money_saving_msg': '做得好！本月您在储蓄。',
    'money_overspend_msg': '本月支出超过收入。',
    'money_no_income_cats': '本月暂无收入类别。',
    'money_no_expense_cats': '本月暂无支出类别。',
    'money_income_by_cat': '按类别的收入',
    'money_expenses_by_cat': '按类别的支出',
    'money_6mo_trend': '6个月趋势',

    'budget_delete_title': '删除预算',
    'budget_total_this_month': '本月总预算',
    'budget_alert': '预算提醒',
    'budget_alert_prefix': '您即将达到限额于',
    'budget_alert_cat_one': '个类别',
    'budget_alert_cat_many': '个类别',
    'budget_categories': '预算类别',
    'budget_view_all': '查看全部',
    'budget_all_categories': '所有预算类别',
    'budget_none_title': '尚未创建预算',
    'budget_none_body': '为您的支出类别设定每月限额\n以保持进度。',
    'budget_create_btn': '创建预算',
    'budget_period_weekly': '每周',
    'budget_period_monthly': '每月',
    'budget_period_yearly': '每年',
    'budget_over_by': '超出预算',
    'budget_used': '已用',
    'budget_left': '剩余',
    'budget_tx_one': '笔交易',
    'budget_tx_many': '笔交易',
  };

  // ── Japanese ───────────────────────────────────────────────────────────────

  static const _ja = <String, String>{
    'cancel': 'キャンセル',
    'save': '保存',
    'delete': '削除',
    'remove': '削除',
    'add': '追加',
    'yes': 'はい',
    'no': 'いいえ',
    'error': 'エラー',
    'required': '必須',
    'none': 'なし',
    'leave': '退出',

    'nav_home': 'ホーム',
    'nav_history': '履歴',
    'nav_money': 'マネー',
    'nav_budget': '予算',
    'nav_family': '家族',
    'nav_goals': '目標',

    'home_welcome': 'お帰りなさい、',
    'home_total_balance': '総残高',
    'home_spending_overview': '支出の概要',
    'home_recent_transactions': '最近の取引',
    'home_see_all': 'すべて表示',
    'home_no_transactions': '取引はありません',
    'home_income': '収入',
    'home_expenses': '支出',
    'home_savings': '貯蓄',
    'home_today': '今日',
    'home_yesterday': '昨日',
    'home_days_ago': '日前',
    'home_this_month': '今月',
    'home_this_month_btn': '今月',
    'home_savings_rate': '貯蓄率',

    'history_title': '取引履歴',
    'history_search': '取引を検索...',
    'history_filter': 'フィルター',
    'history_sort': '並び替え',
    'history_date': '日付',
    'history_total_income': '総収入',
    'history_total_expenses': '総支出',
    'history_all_transactions': 'すべての取引',
    'history_no_transactions': '取引はありません',
    'history_add_transaction': '取引を追加',
    'history_name': '名前',
    'history_amount': '金額',
    'history_category': 'カテゴリ',
    'history_note_optional': 'メモ（任意）',
    'history_save_transaction': '保存',
    'history_income': '収入',
    'history_expense': '支出',
    'history_transfer': '送金',
    'history_filter_by_type': 'タイプで絞り込み',
    'history_sort_by': '並び替え',
    'history_date_range': '日付範囲',
    'history_all': 'すべて',
    'history_newest': '新しい順',
    'history_oldest': '古い順',
    'history_highest': '金額が高い順',
    'history_lowest': '金額が低い順',
    'history_all_time': 'すべての期間',
    'history_last_month': '先月',
    'history_last_7': '過去7日間',
    'history_last_7_label': '7日',
    'history_last_30': '過去30日間',
    'history_last_30_label': '30日',
    'history_new_category': '+ 新しいカテゴリ',
    'history_apply_goal': '目標に適用（任意）',
    'history_valid_amount': '有効な金額を入力してください。',
    'history_failed_save': '保存に失敗しました。',

    'goals_title': '財務目標',
    'goals_subtitle': '財務の夢を追跡',
    'goals_overall_progress': '全体の進捗',
    'goals_target': '目標',
    'goals_pct_achieved': '目標達成',
    'goals_active': 'アクティブな目標',
    'goals_completed': '達成済みの目標',
    'goals_insights': '目標の分析',
    'goals_none_title': '目標がまだありません',
    'goals_none_body': '財務目標を設定して進捗を追跡し、\nモチベーションを保ちましょう。',
    'goals_add_first': '最初の目標を追加',
    'goals_monthly': '月々の拠出',
    'goals_remaining': '残り',
    'goals_complete': '完了',
    'goals_progress': '進捗',
    'goals_delete_title': '目標を削除',
    'goals_delete_body': 'この操作は取り消せません。',
    'goals_add_title': '新しい目標',
    'goals_name': '目標名',
    'goals_target_amount': '目標金額 (\$)',
    'goals_current_savings': '現在の貯蓄 (\$)',
    'goals_monthly_optional': '月々の拠出 (\$、任意)',
    'goals_type': '目標タイプ',
    'goals_target_date': '目標日',
    'goals_note_optional': 'メモ（任意）',
    'goals_create': '目標を作成',
    'goals_update_prefix': '更新：',
    'goals_current_amount': '現在の金額 (\$)',
    'goals_save_progress': '進捗を保存',
    'goals_decrease_title': '金額を減らす',
    'goals_correction': '修正',
    'goals_withdrawal': '引き出し',
    'goals_type_emergency': '緊急資金',
    'goals_type_saving': '貯蓄',
    'goals_type_purchase': '購入',
    'goals_type_retirement': '退職',
    'goals_type_debt': '借金返済',
    'goals_type_investment': '投資',
    'goals_type_spending': '支出',
    'goals_label_emergency': '緊急',
    'goals_label_saving': '貯蓄',
    'goals_label_purchase': '購入',
    'goals_label_retirement': '退職',
    'goals_label_debt': '借金',
    'goals_label_investment': '投資',
    'goals_label_spending': '支出',

    'family_plan': '家族プラン',
    'family_budget': '家族予算',
    'family_spent': '使用済み',
    'family_members': '家族メンバー',
    'family_shared_expenses': '共有費用',
    'family_insights': '家族の分析',
    'family_setup_title': '家族プランを作成',
    'family_setup_body': '家族と一緒に予算と\n共有費用を追跡しましょう。',
    'family_create_btn': '家族プランを作成',
    'family_no_members': 'メンバーがいません。最初のメンバーを追加！',
    'family_no_expenses': '共有費用がありません。追加してください！',
    'family_admin': '管理者',
    'family_member': 'メンバー',
    'family_add_member_title': 'メンバーを追加',
    'family_add_member_hint': '登録時に使用したメールで検索。',
    'family_email': 'メールアドレス',
    'family_look_up': '検索',
    'family_not_found': 'そのメールのアカウントが見つかりません。',
    'family_already_member': 'は既にこのグループにいます。',
    'family_budget_alloc': '予算配分 (\$)',
    'family_add_to_plan': 'プランに追加',
    'family_add_expense_title': '共有費用を追加',
    'family_expense_name': '費用名',
    'family_amount': '金額 (\$)',
    'family_paid_by': '支払者',
    'family_category': 'カテゴリ',
    'family_add_expense_btn': '費用を追加',
    'family_settings_title': 'グループ設定',
    'family_total_budget': '家族総予算 (\$)',
    'family_save_changes': '変更を保存',
    'family_group_name': '家族名',
    'family_personal_budget': '個人予算 (\$)',
    'family_create_plan_btn': 'プランを作成',
    'family_remove_title': 'メンバーを削除',
    'family_cannot_remove_admin': '管理者は削除できません。',
    'family_remove': '削除',
    'family_delete_expense_title': '費用を削除',
    'family_add_members_first': '費用を記録する前にメンバーを追加してください。',
    'family_leave_title': 'グループを退出',
    'family_leave_confirm': 'この家族グループを退出しますか？',
    'family_leave_btn': '退出',
    'family_per_person': '/人',
    'family_of': '/',
    'family_paid_by_prefix': '支払者：',

    'profile_title': 'プロフィールと設定',
    'profile_account': 'アカウント',
    'profile_edit': 'プロフィール編集',
    'profile_change_password': 'パスワード変更',
    'profile_2fa': '二段階認証',
    'profile_preferences': '環境設定',
    'profile_notifications': '通知',
    'profile_dark_mode': 'ダークモード',
    'profile_language': '言語',
    'profile_support': 'サポート',
    'profile_help': 'ヘルプとサポート',
    'profile_privacy': 'プライバシーポリシー',
    'profile_about': 'について',
    'profile_logout': 'ログアウト',

    'budget_title': '予算トラッカー',
    'budget_add': '予算を追加',
    'budget_total': '総予算',
    'budget_spent': '使用済み',
    'budget_remaining': '残り',
    'budget_no_budgets': '予算がありません',
    'budget_over': '予算超過',
    'budget_on_track': '順調',
    'budget_near_limit': '上限近く',

    'money_title': 'マネーフロー',
    'money_income': '収入',
    'money_expenses': '支出',
    'money_net': '純収支',
    'money_failed_load': 'データの読み込みに失敗しました',
    'money_retry': '再試行',
    'money_tab_overview': '概要',
    'money_net_cash_flow': '純キャッシュフロー',
    'money_saving_msg': 'よくできました！今月は貯蓄しています。',
    'money_overspend_msg': '今月は支出が収入を上回っています。',
    'money_no_income_cats': '今月の収入カテゴリはありません。',
    'money_no_expense_cats': '今月の支出カテゴリはありません。',
    'money_income_by_cat': 'カテゴリ別収入',
    'money_expenses_by_cat': 'カテゴリ別支出',
    'money_6mo_trend': '6ヶ月の傾向',

    'budget_delete_title': '予算を削除',
    'budget_total_this_month': '今月の総予算',
    'budget_alert': '予算アラート',
    'budget_alert_prefix': '次のカテゴリで限度に近づいています:',
    'budget_alert_cat_one': 'カテゴリ',
    'budget_alert_cat_many': 'カテゴリ',
    'budget_categories': '予算カテゴリ',
    'budget_view_all': 'すべて表示',
    'budget_all_categories': 'すべての予算カテゴリ',
    'budget_none_title': '予算がまだ作成されていません',
    'budget_none_body': '支出カテゴリの月次上限を設定して\n計画的に管理しましょう。',
    'budget_create_btn': '予算を作成',
    'budget_period_weekly': '週次',
    'budget_period_monthly': '月次',
    'budget_period_yearly': '年次',
    'budget_over_by': '予算超過',
    'budget_used': '使用',
    'budget_left': '残り',
    'budget_tx_one': '件の取引',
    'budget_tx_many': '件の取引',
  };

  // ── Vietnamese ─────────────────────────────────────────────────────────────

  static const _vi = <String, String>{
    'cancel': 'Hủy',
    'save': 'Lưu',
    'delete': 'Xóa',
    'remove': 'Gỡ bỏ',
    'add': 'Thêm',
    'yes': 'Có',
    'no': 'Không',
    'error': 'Lỗi',
    'required': 'Bắt buộc',
    'none': 'Không có',
    'leave': 'Rời',

    'nav_home': 'Trang chủ',
    'nav_history': 'Lịch sử',
    'nav_money': 'Tiền',
    'nav_budget': 'Ngân sách',
    'nav_family': 'Gia đình',
    'nav_goals': 'Mục tiêu',

    'home_welcome': 'Chào mừng trở lại,',
    'home_total_balance': 'Tổng số dư',
    'home_spending_overview': 'Tổng quan chi tiêu',
    'home_recent_transactions': 'Giao dịch gần đây',
    'home_see_all': 'Xem tất cả',
    'home_no_transactions': 'Chưa có giao dịch',
    'home_income': 'Thu nhập',
    'home_expenses': 'Chi tiêu',
    'home_savings': 'Tiết kiệm',
    'home_today': 'Hôm nay',
    'home_yesterday': 'Hôm qua',
    'home_days_ago': 'ngày trước',
    'home_this_month': 'Tháng này',
    'home_this_month_btn': 'Tháng này',
    'home_savings_rate': 'Tỷ lệ tiết kiệm',

    'history_title': 'Lịch sử giao dịch',
    'history_search': 'Tìm kiếm giao dịch...',
    'history_filter': 'Lọc',
    'history_sort': 'Sắp xếp',
    'history_date': 'Ngày',
    'history_total_income': 'Tổng thu nhập',
    'history_total_expenses': 'Tổng chi tiêu',
    'history_all_transactions': 'TẤT CẢ GIAO DỊCH',
    'history_no_transactions': 'Chưa có giao dịch',
    'history_add_transaction': 'Thêm giao dịch',
    'history_name': 'Tên',
    'history_amount': 'Số tiền',
    'history_category': 'Danh mục',
    'history_note_optional': 'Ghi chú (tùy chọn)',
    'history_save_transaction': 'Lưu',
    'history_income': 'Thu nhập',
    'history_expense': 'Chi tiêu',
    'history_transfer': 'Chuyển khoản',
    'history_filter_by_type': 'Lọc theo loại',
    'history_sort_by': 'Sắp xếp theo',
    'history_date_range': 'Khoảng ngày',
    'history_all': 'Tất cả',
    'history_newest': 'Mới nhất trước',
    'history_oldest': 'Cũ nhất trước',
    'history_highest': 'Số tiền cao nhất',
    'history_lowest': 'Số tiền thấp nhất',
    'history_all_time': 'Mọi lúc',
    'history_last_month': 'Tháng trước',
    'history_last_7': '7 ngày qua',
    'history_last_7_label': '7 ngày',
    'history_last_30': '30 ngày qua',
    'history_last_30_label': '30 ngày',
    'history_new_category': '+ Danh mục mới',
    'history_apply_goal': 'Áp dụng cho mục tiêu (tùy chọn)',
    'history_valid_amount': 'Nhập số tiền hợp lệ.',
    'history_failed_save': 'Lưu thất bại.',

    'goals_title': 'Mục tiêu tài chính',
    'goals_subtitle': 'Theo dõi ước mơ tài chính',
    'goals_overall_progress': 'Tiến độ tổng thể',
    'goals_target': 'Mục tiêu',
    'goals_pct_achieved': 'mục tiêu đã đạt',
    'goals_active': 'Đang hoạt động',
    'goals_completed': 'Đã hoàn thành',
    'goals_insights': 'Phân tích mục tiêu',
    'goals_none_title': 'Chưa có mục tiêu',
    'goals_none_body': 'Đặt mục tiêu tài chính để theo dõi tiến độ\nvà duy trì động lực.',
    'goals_add_first': 'Mục tiêu đầu tiên',
    'goals_monthly': 'Đóng góp hàng tháng',
    'goals_remaining': 'còn lại',
    'goals_complete': 'hoàn thành',
    'goals_progress': 'Tiến độ',
    'goals_delete_title': 'Xóa mục tiêu',
    'goals_delete_body': 'Hành động này không thể hoàn tác.',
    'goals_add_title': 'Mục tiêu mới',
    'goals_name': 'Tên mục tiêu',
    'goals_target_amount': 'Số tiền mục tiêu (\$)',
    'goals_current_savings': 'Tiết kiệm hiện tại (\$)',
    'goals_monthly_optional': 'Đóng góp hàng tháng (\$, tùy chọn)',
    'goals_type': 'Loại mục tiêu',
    'goals_target_date': 'Ngày mục tiêu',
    'goals_note_optional': 'Ghi chú (tùy chọn)',
    'goals_create': 'Tạo mục tiêu',
    'goals_update_prefix': 'Cập nhật:',
    'goals_current_amount': 'Số tiền hiện tại (\$)',
    'goals_save_progress': 'Lưu tiến độ',
    'goals_decrease_title': 'Giảm số tiền',
    'goals_correction': 'Sửa lỗi',
    'goals_withdrawal': 'Rút tiền',
    'goals_type_emergency': 'Quỹ khẩn cấp',
    'goals_type_saving': 'Tiết kiệm',
    'goals_type_purchase': 'Mua sắm',
    'goals_type_retirement': 'Hưu trí',
    'goals_type_debt': 'Trả nợ',
    'goals_type_investment': 'Đầu tư',
    'goals_type_spending': 'Chi tiêu',
    'goals_label_emergency': 'Khẩn cấp',
    'goals_label_saving': 'Tiết kiệm',
    'goals_label_purchase': 'Mua sắm',
    'goals_label_retirement': 'Hưu trí',
    'goals_label_debt': 'Nợ',
    'goals_label_investment': 'Đầu tư',
    'goals_label_spending': 'Chi tiêu',

    'family_plan': 'Kế hoạch gia đình',
    'family_budget': 'Ngân sách gia đình',
    'family_spent': 'Đã chi',
    'family_members': 'Thành viên gia đình',
    'family_shared_expenses': 'Chi phí chung',
    'family_insights': 'Phân tích gia đình',
    'family_setup_title': 'Tạo kế hoạch gia đình',
    'family_setup_body': 'Theo dõi ngân sách và chi phí chung\nvới các thành viên gia đình.',
    'family_create_btn': 'Tạo kế hoạch gia đình',
    'family_no_members': 'Chưa có thành viên. Thêm thành viên đầu tiên!',
    'family_no_expenses': 'Chưa có chi phí chung. Thêm chi phí đầu tiên!',
    'family_admin': 'Quản trị viên',
    'family_member': 'Thành viên',
    'family_add_member_title': 'Thêm thành viên',
    'family_add_member_hint': 'Tìm bằng email đã đăng ký.',
    'family_email': 'Địa chỉ email',
    'family_look_up': 'Tra cứu',
    'family_not_found': 'Không tìm thấy tài khoản với email đó.',
    'family_already_member': 'đã ở trong nhóm này.',
    'family_budget_alloc': 'Phân bổ ngân sách (\$)',
    'family_add_to_plan': 'Thêm vào kế hoạch',
    'family_add_expense_title': 'Thêm chi phí chung',
    'family_expense_name': 'Tên chi phí',
    'family_amount': 'Số tiền (\$)',
    'family_paid_by': 'Người trả',
    'family_category': 'Danh mục',
    'family_add_expense_btn': 'Thêm chi phí',
    'family_settings_title': 'Cài đặt nhóm',
    'family_total_budget': 'Tổng ngân sách gia đình (\$)',
    'family_save_changes': 'Lưu thay đổi',
    'family_group_name': 'Tên gia đình',
    'family_personal_budget': 'Ngân sách cá nhân (\$)',
    'family_create_plan_btn': 'Tạo kế hoạch',
    'family_remove_title': 'Gỡ thành viên',
    'family_cannot_remove_admin': 'Không thể gỡ quản trị viên.',
    'family_remove': 'Gỡ bỏ',
    'family_delete_expense_title': 'Xóa chi phí',
    'family_add_members_first': 'Thêm thành viên trước khi ghi chi phí.',
    'family_leave_title': 'Rời nhóm',
    'family_leave_confirm': 'Rời nhóm gia đình này?',
    'family_leave_btn': 'Rời',
    'family_per_person': '/người',
    'family_of': 'của',
    'family_paid_by_prefix': 'Trả bởi',

    'profile_title': 'Hồ sơ & Cài đặt',
    'profile_account': 'Tài khoản',
    'profile_edit': 'Sửa hồ sơ',
    'profile_change_password': 'Đổi mật khẩu',
    'profile_2fa': 'Xác thực hai yếu tố',
    'profile_preferences': 'Tùy chọn',
    'profile_notifications': 'Thông báo',
    'profile_dark_mode': 'Chế độ tối',
    'profile_language': 'Ngôn ngữ',
    'profile_support': 'Hỗ trợ',
    'profile_help': 'Trợ giúp & Hỗ trợ',
    'profile_privacy': 'Chính sách bảo mật',
    'profile_about': 'Giới thiệu',
    'profile_logout': 'Đăng xuất',

    'budget_title': 'Theo dõi ngân sách',
    'budget_add': 'Thêm ngân sách',
    'budget_total': 'Tổng ngân sách',
    'budget_spent': 'Đã chi',
    'budget_remaining': 'Còn lại',
    'budget_no_budgets': 'Chưa có ngân sách',
    'budget_over': 'Vượt ngân sách',
    'budget_on_track': 'Đúng tiến độ',
    'budget_near_limit': 'Gần giới hạn',

    'money_title': 'Dòng tiền',
    'money_income': 'Thu nhập',
    'money_expenses': 'Chi tiêu',
    'money_net': 'Dòng tiền ròng',
    'money_failed_load': 'Không tải được dữ liệu',
    'money_retry': 'Thử lại',
    'money_tab_overview': 'Tổng quan',
    'money_net_cash_flow': 'Dòng tiền ròng',
    'money_saving_msg': 'Tuyệt vời! Bạn đang tiết kiệm tháng này.',
    'money_overspend_msg': 'Chi tiêu vượt thu nhập tháng này.',
    'money_no_income_cats': 'Không có danh mục thu nhập tháng này.',
    'money_no_expense_cats': 'Không có danh mục chi tiêu tháng này.',
    'money_income_by_cat': 'Thu nhập theo danh mục',
    'money_expenses_by_cat': 'Chi tiêu theo danh mục',
    'money_6mo_trend': 'Xu hướng 6 tháng',

    'budget_delete_title': 'Xóa ngân sách',
    'budget_total_this_month': 'Tổng ngân sách tháng này',
    'budget_alert': 'Cảnh báo ngân sách',
    'budget_alert_prefix': 'Bạn đang gần giới hạn trong',
    'budget_alert_cat_one': 'danh mục',
    'budget_alert_cat_many': 'danh mục',
    'budget_categories': 'Danh mục ngân sách',
    'budget_view_all': 'Xem tất cả',
    'budget_all_categories': 'Tất cả danh mục',
    'budget_none_title': 'Chưa tạo ngân sách',
    'budget_none_body': 'Đặt giới hạn hàng tháng cho các danh mục\nchi tiêu để giữ đúng tiến độ.',
    'budget_create_btn': 'Tạo ngân sách',
    'budget_period_weekly': 'Hàng tuần',
    'budget_period_monthly': 'Hàng tháng',
    'budget_period_yearly': 'Hàng năm',
    'budget_over_by': 'Vượt ngân sách',
    'budget_used': 'đã dùng',
    'budget_left': 'còn lại',
    'budget_tx_one': 'giao dịch',
    'budget_tx_many': 'giao dịch',
  };
}
